sudo: required

language: c

dist: bionic

services:
    - docker

compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq clang-tools-6.0 curl gdb lcov libarchive-dev libtalloc-dev sloccount strace swig uthash-dev

script:
  - sloccount --details .
  - make -C src loader.elf loader-m32.elf build.h 
  - env CFLAGS=--coverage LDFLAGS='--coverage' make -C src proot care
  - env PATH=/bin:/usr/bin:/sbin:/usr/sbin:$PWD/src PROOT_NO_SECCOMP=1 make -C test

