name: Ubuntu

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Test ${{ matrix.SECCOMP == '1' && 'With seccomp' || 'No seccomp' }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SECCOMP: [ 0, 1 ]
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq clang-tools-6.0 curl gdb lcov libarchive-dev libtalloc-dev sloccount strace swig uthash-dev python3-dev

      - name: Info
        run: sloccount --details .

      - name: Build
        run: |
          make -C src loader.elf loader-m32.elf build.h
          env CFLAGS=--coverage LDFLAGS=--coverage make -C src proot care V=1

      - name: Test
        run: |
          env ${{ matrix.SECCOMP == '0' && 'PROOT_NO_SECCOMP=1' || '' }} PATH=/bin:/usr/bin:/sbin:/usr/sbin:$PWD/src make -C test -j $(nproc) QUIET_LOG=$PWD/test.log

      - name: Test log
        if: always()
        run: ([ -f test.log ] && cat test.log) || true
